services:
  server:
    container_name: server
    build:
      context: ./server
    restart: always
    ports:
      - "3001:3001"
    env_file:
      - ./server/.env
    volumes:
      - data-volume:/app/dist/dev.db
  client:
    container_name: client
    build:
      context: ./client
    restart: always
    ports:
      - "80:80"
      - "443:443"

networks:
  app-networks:
    driver: bridge

volumes:
  data-volume:

    #   frontend: 
    #     build:
    #       context: ./client
    #       dockerfile: Dockerfile
    #     ports:
    #       - "80:80"
    #     volumes:
    #       - frontend:/app/node_modules


    # volumes:
    #   frontend:
